# See: https://circleci.com/docs/2.0/language-python/

version: 2.0

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/python:3.10

    steps:
      - checkout

      - run:
          name: Update apt-get
          command: sudo apt-get update

      - run:
          name: Install Graphviz
          command: sudo apt-get install graphviz libgraphviz-dev

      - run:
          name: Install TeX
          command: sudo apt-get install texlive texlive-latex-extra latexmk imagemagick

      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip wheel setuptools
            pip install -U -r requirements/doc.txt
            pip list

      - run:
          name: Install
          command: |
            source venv/bin/activate
            pip install .

      - run:
          name: Build docs
          command: |
            source venv/bin/activate
            make -C doc/ dist

      - store_artifacts:
          path: doc/build/dist
