/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.20
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGPYTHON

#include "Python.h"

/*************************************************************** -*- c -*-
 * python/precommon.swg
 *
 * Rename all exported symbols from common.swg, to avoid symbol
 * clashes if multiple interpreters are included
 *
 ************************************************************************/

#define SWIG_TypeRegister    SWIG_Python_TypeRegister
#define SWIG_TypeCheck       SWIG_Python_TypeCheck
#define SWIG_TypeCast        SWIG_Python_TypeCast
#define SWIG_TypeDynamicCast SWIG_Python_TypeDynamicCast
#define SWIG_TypeName        SWIG_Python_TypeName
#define SWIG_TypeQuery       SWIG_Python_TypeQuery
#define SWIG_TypeClientData  SWIG_Python_TypeClientData
#define SWIG_PackData        SWIG_Python_PackData 
#define SWIG_UnpackData      SWIG_Python_UnpackData 


/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/

#include <string.h>

#if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#  if defined(_MSC_VER) || defined(__GNUC__)
#    if defined(STATIC_LINKED)
#      define SWIGEXPORT(a) a
#      define SWIGIMPORT(a) extern a
#    else
#      define SWIGEXPORT(a) __declspec(dllexport) a
#      define SWIGIMPORT(a) extern a
#    endif
#  else
#    if defined(__BORLANDC__)
#      define SWIGEXPORT(a) a _export
#      define SWIGIMPORT(a) a _export
#    else
#      define SWIGEXPORT(a) a
#      define SWIGIMPORT(a) a
#    endif
#  endif
#else
#  define SWIGEXPORT(a) a
#  define SWIGIMPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#  define SWIGRUNTIME(a) SWIGEXPORT(a)
#else
#  define SWIGRUNTIME(a) static a
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *);
typedef struct swig_type_info *(*swig_dycast_func)(void **);

typedef struct swig_type_info {
  const char             *name;
  swig_converter_func     converter;
  const char             *str;
  void                   *clientdata;
  swig_dycast_func        dcast;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
} swig_type_info;

#ifdef SWIG_NOINCLUDE

SWIGIMPORT(swig_type_info *) SWIG_TypeRegister(swig_type_info *);
SWIGIMPORT(swig_type_info *) SWIG_TypeCheck(char *c, swig_type_info *);
SWIGIMPORT(void *)           SWIG_TypeCast(swig_type_info *, void *);
SWIGIMPORT(swig_type_info *) SWIG_TypeDynamicCast(swig_type_info *, void **);
SWIGIMPORT(const char *)     SWIG_TypeName(const swig_type_info *);
SWIGIMPORT(swig_type_info *) SWIG_TypeQuery(const char *);
SWIGIMPORT(void)             SWIG_TypeClientData(swig_type_info *, void *);
SWIGIMPORT(char *)           SWIG_PackData(char *, void *, int);
SWIGIMPORT(char *)           SWIG_UnpackData(char *, void *, int);

#else

static swig_type_info *swig_type_list = 0;

/* Register a type mapping with the type-checking */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeRegister(swig_type_info *ti) {
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = swig_type_list;
  while (tc) {
    if (strcmp(tc->name, ti->name) == 0) {
      /* Already exists in the table.  Just add additional types to the list */
      if (tc->clientdata) ti->clientdata = tc->clientdata;
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = swig_type_list;
  swig_type_list = ti;

  /* Build linked lists */
  l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  if (next) next->prev = head;
  head->next = next;
  return ret;
}

/* Check the typename */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeCheck(char *c, swig_type_info *ty) {
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  do {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
        s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      s->prev = ty;
      return s;
    }
    s = s->next;
  } while (s && (s != ty->next));
  return 0;
}

/* Cast a pointer up an inheritance hierarchy */
SWIGRUNTIME(void *) 
SWIG_TypeCast(swig_type_info *ty, void *ptr) {
  if ((!ty) || (!ty->converter)) return ptr;
  return (*ty->converter)(ptr);
}

/* Dynamic pointer casting. Down an inheritance hierarchy */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeDynamicCast(swig_type_info *ty, void **ptr) {
  swig_type_info *lastty = ty;
  if (!ty || !ty->dcast) return ty;
  while (ty && (ty->dcast)) {
    ty = (*ty->dcast)(ptr);
    if (ty) lastty = ty;
  }
  return lastty;
}

/* Return the name associated with this type */
SWIGRUNTIME(const char *)
SWIG_TypeName(const swig_type_info *ty) {
  return ty->name;
}

/* Search for a swig_type_info structure */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeQuery(const char *name) {
  swig_type_info *ty = swig_type_list;
  while (ty) {
    if (ty->str && (strcmp(name,ty->str) == 0)) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

/* Set the clientdata field for a type */
SWIGRUNTIME(void)
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  swig_type_info *tc, *equiv;
  if (ti->clientdata == clientdata) return;
  ti->clientdata = clientdata;
  equiv = ti->next;
  while (equiv) {
    if (!equiv->converter) {
      tc = swig_type_list;
      while (tc) {
        if ((strcmp(tc->name, equiv->name) == 0))
          SWIG_TypeClientData(tc,clientdata);
        tc = tc->prev;
      }
    }
    equiv = equiv->next;
  }
}

/* Pack binary data into a string */
SWIGRUNTIME(char *)
SWIG_PackData(char *c, void *ptr, int sz) {
  static char hex[17] = "0123456789abcdef";
  int i;
  unsigned char *u = (unsigned char *) ptr;
  register unsigned char uu;
  for (i = 0; i < sz; i++,u++) {
    uu = *u;
    *(c++) = hex[(uu & 0xf0) >> 4];
    *(c++) = hex[uu & 0xf];
  }
  return c;
}

/* Unpack binary data from a string */
SWIGRUNTIME(char *)
SWIG_UnpackData(char *c, void *ptr, int sz) {
  register unsigned char uu = 0;
  register int d;
  unsigned char *u = (unsigned char *) ptr;
  int i;
  for (i = 0; i < sz; i++, u++) {
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu = ((d - '0') << 4);
    else if ((d >= 'a') && (d <= 'f'))
      uu = ((d - ('a'-10)) << 4);
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu |= (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      uu |= (d - ('a'-10));
    *u = uu;
  }
  return c;
}

#endif

#ifdef __cplusplus
}
#endif

/***********************************************************************
 * python.swg
 *
 *     This file contains the runtime support for Python modules
 *     and includes code for managing global variables and pointer
 *     type checking.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 ************************************************************************/

#include "Python.h"

#ifdef __cplusplus
extern "C" {
#endif

#define SWIG_PY_INT     1
#define SWIG_PY_FLOAT   2
#define SWIG_PY_STRING  3
#define SWIG_PY_POINTER 4
#define SWIG_PY_BINARY  5

/* Flags for pointer conversion */

#define SWIG_POINTER_EXCEPTION     0x1
#define SWIG_POINTER_DISOWN        0x2

/* Exception handling in wrappers */
#define SWIG_fail   goto fail

/* Constant information structure */
typedef struct swig_const_info {
    int type;
    char *name;
    long lvalue;
    double dvalue;
    void   *pvalue;
    swig_type_info **ptype;
} swig_const_info;

/* Common SWIG API */
#define SWIG_ConvertPtr(obj, pp, type, flags) \
  SWIG_Python_ConvertPtr(obj, pp, type, flags)
#define SWIG_NewPointerObj(p, type, flags) \
  SWIG_Python_NewPointerObj(p, type, flags)
#define SWIG_MustGetPtr(p, type, argnum, flags) \
  SWIG_Python_MustGetPtr(p, type, argnum, flags)

/* Python-specific SWIG API */
#define SWIG_newvarlink() \
  SWIG_Python_newvarlink()
#define SWIG_addvarlink(p, name, get_attr, set_attr) \
  SWIG_Python_addvarlink(p, name, get_attr, set_attr)
#define SWIG_ConvertPacked(obj, ptr, sz, ty, flags) \
  SWIG_Python_ConvertPacked(obj, ptr, sz, ty, flags)
#define SWIG_NewPackedObj(ptr, sz, type) \
  SWIG_Python_NewPackedObj(ptr, sz, type)
#define SWIG_InstallConstants(d, constants) \
  SWIG_Python_InstallConstants(d, constants)

#ifdef SWIG_NOINCLUDE

SWIGIMPORT(int)               SWIG_Python_ConvertPtr(PyObject *, void **, swig_type_info *, int);
SWIGIMPORT(PyObject *)        SWIG_Python_NewPointerObj(void *, swig_type_info *,int own);
SWIGIMPORT(void *)            SWIG_Python_MustGetPtr(PyObject *, swig_type_info *, int, int);
SWIGIMPORT(PyObject *)        SWIG_Python_newvarlink(void);
SWIGIMPORT(void)              SWIG_Python_addvarlink(PyObject *, char *, PyObject *(*)(void), int (*)(PyObject *));
SWIGIMPORT(int)               SWIG_Python_ConvertPacked(PyObject *, void *, int sz, swig_type_info *, int);
SWIGIMPORT(PyObject *)        SWIG_Python_NewPackedObj(void *, int sz, swig_type_info *);
SWIGIMPORT(void)              SWIG_Python_InstallConstants(PyObject *d, swig_const_info constants[]);

#else

/* -----------------------------------------------------------------------------
 * global variable support code.
 * ----------------------------------------------------------------------------- */

typedef struct swig_globalvar {   
  char       *name;                  /* Name of global variable */
  PyObject *(*get_attr)(void);       /* Return the current value */
  int       (*set_attr)(PyObject *); /* Set the value */
  struct swig_globalvar *next;
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar *vars;
} swig_varlinkobject;

static PyObject *
swig_varlink_repr(swig_varlinkobject *v) {
  v = v;
  return PyString_FromString("<Global variables>");
}

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags) {
  swig_globalvar  *var;
  flags = flags;
  fprintf(fp,"Global variables { ");
  for (var = v->vars; var; var=var->next) {
    fprintf(fp,"%s", var->name);
    if (var->next) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->get_attr)();
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return NULL;
}

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->set_attr)(p);
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return 1;
}

statichere PyTypeObject varlinktype = {
  PyObject_HEAD_INIT(0)              
  0,
  (char *)"swigvarlink",              /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */
SWIGRUNTIME(PyObject *)
SWIG_Python_newvarlink(void) {
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  result->vars = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGRUNTIME(void)
SWIG_Python_addvarlink(PyObject *p, char *name, PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p)) {
  swig_varlinkobject *v;
  swig_globalvar *gv;
  v= (swig_varlinkobject *) p;
  gv = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  gv->name = (char *) malloc(strlen(name)+1);
  strcpy(gv->name,name);
  gv->get_attr = get_attr;
  gv->set_attr = set_attr;
  gv->next = v->vars;
  v->vars = gv;
}

/* Convert a pointer value */
SWIGRUNTIME(int)
SWIG_Python_ConvertPtr(PyObject *obj, void **ptr, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c = 0;
  static PyObject *SWIG_this = 0;
  int    newref = 0;
  PyObject  *pyobj = 0;

  if (!obj) return 0;
  if (obj == Py_None) {
    *ptr = 0;
    return 0;
  }
#ifdef SWIG_COBJECT_TYPES
  if (!(PyCObject_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_FromString("this");
    pyobj = obj;
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyCObject_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  }  
  *ptr = PyCObject_AsVoidPtr(obj);
  c = (char *) PyCObject_GetDesc(obj);
  if (newref) Py_DECREF(obj);
  goto cobject;
#else
  if (!(PyString_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_FromString("this");
    pyobj = obj;
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyString_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  } 
  c = PyString_AsString(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') {
    *ptr = (void *) 0;
    if (strcmp(c,"NULL") == 0) {
      if (newref) { Py_DECREF(obj); }
      return 0;
    } else {
      if (newref) { Py_DECREF(obj); }
      goto type_error;
    }
  }
  c++;
  c = SWIG_UnpackData(c,ptr,sizeof(void *));
  if (newref) { Py_DECREF(obj); }
#endif

#ifdef SWIG_COBJECT_TYPES
cobject:
#endif

  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
    *ptr = SWIG_TypeCast(tc,(void*) *ptr);
  }

  if ((pyobj) && (flags & SWIG_POINTER_DISOWN)) {
    PyObject *zero = PyInt_FromLong(0);
    PyObject_SetAttrString(pyobj,(char*)"thisown",zero);
    Py_DECREF(zero);
  }
  return 0;

type_error:
  if (flags & SWIG_POINTER_EXCEPTION) {
    if (ty && c) {
      char *temp = (char *) malloc(64+strlen(ty->name)+strlen(c));
      sprintf(temp,"Type error. Got %s, expected %s", c, ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Convert a pointer value, signal an exception on a type mismatch */
SWIGRUNTIME(void *)
SWIG_Python_MustGetPtr(PyObject *obj, swig_type_info *ty, int argnum, int flags) {
  void *result;
  SWIG_Python_ConvertPtr(obj, &result, ty, flags | SWIG_POINTER_EXCEPTION);
  return result;
}

/* Convert a packed value value */
SWIGRUNTIME(int)
SWIG_Python_ConvertPacked(PyObject *obj, void *ptr, int sz, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c = 0;

  if ((!obj) || (!PyString_Check(obj))) goto type_error;
  c = PyString_AsString(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') goto type_error;
  c++;
  c = SWIG_UnpackData(c,ptr,sz);
  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
  }
  return 0;

type_error:

  if (flags) {
    if (ty && c) {
      char *temp = (char *) malloc(64+strlen(ty->name)+strlen(c));
      sprintf(temp,"Type error. Got %s, expected %s", c, ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Create a new pointer object */
SWIGRUNTIME(PyObject *)
SWIG_Python_NewPointerObj(void *ptr, swig_type_info *type, int own) {
  PyObject *robj;
  if (!ptr) {
    Py_INCREF(Py_None);
    return Py_None;
  }
#ifdef SWIG_COBJECT_TYPES
  robj = PyCObject_FromVoidPtrAndDesc((void *) ptr, (char *) type->name, NULL);
#else
  {
    char result[1024];
    char *r = result;
    *(r++) = '_';
    r = SWIG_PackData(r,&ptr,sizeof(void *));
    strcpy(r,type->name);
    robj = PyString_FromString(result);
  }
#endif
  if (!robj || (robj == Py_None)) return robj;
  if (type->clientdata) {
    PyObject *inst;
    PyObject *args = Py_BuildValue((char*)"(O)", robj);
    Py_DECREF(robj);
    inst = PyObject_CallObject((PyObject *) type->clientdata, args);
    Py_DECREF(args);
    if (inst) {
      if (own) {
        PyObject *n = PyInt_FromLong(1);
        PyObject_SetAttrString(inst,(char*)"thisown",n);
        Py_DECREF(n);
      }
      robj = inst;
    }
  }
  return robj;
}

SWIGRUNTIME(PyObject *)
SWIG_Python_NewPackedObj(void *ptr, int sz, swig_type_info *type) {
  char result[1024];
  char *r = result;
  if ((2*sz + 1 + strlen(type->name)) > 1000) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,ptr,sz);
  strcpy(r,type->name);
  return PyString_FromString(result);
}

/* Install Constants */
SWIGRUNTIME(void)
SWIG_Python_InstallConstants(PyObject *d, swig_const_info constants[]) {
  int i;
  PyObject *obj;
  for (i = 0; constants[i].type; i++) {
    switch(constants[i].type) {
    case SWIG_PY_INT:
      obj = PyInt_FromLong(constants[i].lvalue);
      break;
    case SWIG_PY_FLOAT:
      obj = PyFloat_FromDouble(constants[i].dvalue);
      break;
    case SWIG_PY_STRING:
      obj = PyString_FromString((char *) constants[i].pvalue);
      break;
    case SWIG_PY_POINTER:
      obj = SWIG_NewPointerObj(constants[i].pvalue, *(constants[i]).ptype,0);
      break;
    case SWIG_PY_BINARY:
      obj = SWIG_NewPackedObj(constants[i].pvalue, constants[i].lvalue, *(constants[i].ptype));
      break;
    default:
      obj = 0;
      break;
    }
    if (obj) {
      PyDict_SetItemString(d,constants[i].name,obj);
      Py_DECREF(obj);
    }
  }
}

#endif

/* Contract support */

#define SWIG_contract_assert(expr, msg) if (!(expr)) { PyErr_SetString(PyExc_RuntimeError, (char *) msg ); goto fail; } else

#ifdef __cplusplus
}
#endif


/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_p_FILE swig_types[0] 
#define  SWIGTYPE_p_Agedge_t swig_types[1] 
#define  SWIGTYPE_p_Agsym_t swig_types[2] 
#define  SWIGTYPE_p_Agraph_t swig_types[3] 
#define  SWIGTYPE_p_Agdesc_t swig_types[4] 
#define  SWIGTYPE_p_Agnode_t swig_types[5] 
#define  SWIGTYPE_p_Agdisc_t swig_types[6] 
static swig_type_info *swig_types[8];

/* -------- TYPES TABLE (END) -------- */


/*-----------------------------------------------
              @(target):= _graphviz.so
  ------------------------------------------------*/
#define SWIG_init    init_graphviz

#define SWIG_name    "_graphviz"

#define  SWIG_MemoryError    1
#define  SWIG_IOError        2
#define  SWIG_RuntimeError   3
#define  SWIG_IndexError     4
#define  SWIG_TypeError      5
#define  SWIG_DivisionByZero 6
#define  SWIG_OverflowError  7
#define  SWIG_SyntaxError    8
#define  SWIG_ValueError     9
#define  SWIG_SystemError   10
#define  SWIG_UnknownError  99


static void SWIG_exception_(int code, const char *msg) {
  switch(code) {
  case SWIG_MemoryError:
    PyErr_SetString(PyExc_MemoryError,msg);
    break;
  case SWIG_IOError:
    PyErr_SetString(PyExc_IOError,msg);
    break;
  case SWIG_RuntimeError:
    PyErr_SetString(PyExc_RuntimeError,msg);
    break;
  case SWIG_IndexError:
    PyErr_SetString(PyExc_IndexError,msg);
    break;
  case SWIG_TypeError:
    PyErr_SetString(PyExc_TypeError,msg);
    break;
  case SWIG_DivisionByZero:
    PyErr_SetString(PyExc_ZeroDivisionError,msg);
    break;
  case SWIG_OverflowError:
    PyErr_SetString(PyExc_OverflowError,msg);
    break;
  case SWIG_SyntaxError:
    PyErr_SetString(PyExc_SyntaxError,msg);
    break;
  case SWIG_ValueError:
    PyErr_SetString(PyExc_ValueError,msg);
    break;
  case SWIG_SystemError:
    PyErr_SetString(PyExc_SystemError,msg);
    break;
  default:
    PyErr_SetString(PyExc_RuntimeError,msg);
    break;
  }
}

#define SWIG_exception(a,b) { SWIG_exception_(a,b); SWIG_fail; }


#include "agraph.h"


  char *agattrname(Agsym_t *atsym) {	
    return atsym->name;
  }
  

  char *agattrdefval(Agsym_t *atsym) {
    return atsym->defval;
  }
  
#ifdef __cplusplus
extern "C" {
#endif
static PyObject *_wrap_agopen(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    Agdesc_t arg2 ;
    Agdisc_t *arg3 = (Agdisc_t *) 0 ;
    Agraph_t *result;
    Agdesc_t *argp2 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOO:agopen",&obj0,&obj1,&obj2)) goto fail;
    {
        if (obj0 == Py_None) {
            arg1 = 0;
        } else if (!PyString_Check(obj0)) {
            PyErr_SetString(PyExc_TypeError, "not a valid string");
            return NULL;
        } else arg1 = PyString_AsString(obj0);
    }
    if ((SWIG_ConvertPtr(obj1,(void **) &argp2, SWIGTYPE_p_Agdesc_t,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg2 = *argp2; 
    if ((SWIG_ConvertPtr(obj2,(void **) &arg3, SWIGTYPE_p_Agdisc_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (Agraph_t *)agopen(arg1,arg2,arg3);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Agraph_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agclose(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agraph_t *arg1 = (Agraph_t *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:agclose",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agraph_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)agclose(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agread(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    FILE *arg1 = (FILE *) 0 ;
    Agdisc_t *arg2 = (Agdisc_t *) 0 ;
    Agraph_t *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:agread",&obj0,&obj1)) goto fail;
    {
        if (!PyFile_Check(obj0)) {
            PyErr_SetString(PyExc_TypeError, "not a file handle");
            return NULL;
        }
        arg1 = PyFile_AsFile(obj0);
    }
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Agdisc_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (Agraph_t *)agread(arg1,arg2);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Agraph_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agwrite(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agraph_t *arg1 = (Agraph_t *) 0 ;
    FILE *arg2 = (FILE *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:agwrite",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agraph_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        if (!PyFile_Check(obj1)) {
            PyErr_SetString(PyExc_TypeError, "not a file handle");
            return NULL;
        }
        arg2 = PyFile_AsFile(obj1);
    }
    result = (int)agwrite(arg1,arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agisundirected(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agraph_t *arg1 = (Agraph_t *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:agisundirected",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agraph_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)agisundirected(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agisdirected(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agraph_t *arg1 = (Agraph_t *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:agisdirected",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agraph_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)agisdirected(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agisstrict(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agraph_t *arg1 = (Agraph_t *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:agisstrict",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agraph_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)agisstrict(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agsubg(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agraph_t *arg1 = (Agraph_t *) 0 ;
    char *arg2 ;
    int arg3 ;
    Agraph_t *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOi:agsubg",&obj0,&obj1,&arg3)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agraph_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        if (obj1 == Py_None) {
            arg2 = 0;
        } else if (!PyString_Check(obj1)) {
            PyErr_SetString(PyExc_TypeError, "not a valid string");
            return NULL;
        } else arg2 = PyString_AsString(obj1);
    }
    result = (Agraph_t *)agsubg(arg1,arg2,arg3);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Agraph_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agfstsubg(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agraph_t *arg1 = (Agraph_t *) 0 ;
    Agraph_t *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:agfstsubg",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agraph_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (Agraph_t *)agfstsubg(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Agraph_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agnxtsubg(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agraph_t *arg1 = (Agraph_t *) 0 ;
    Agraph_t *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:agnxtsubg",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agraph_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (Agraph_t *)agnxtsubg(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Agraph_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agparent(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agraph_t *arg1 = (Agraph_t *) 0 ;
    Agraph_t *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:agparent",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agraph_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (Agraph_t *)agparent(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Agraph_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agroot(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agraph_t *arg1 = (Agraph_t *) 0 ;
    Agraph_t *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:agroot",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agraph_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (Agraph_t *)agroot(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Agraph_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agsubnode(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agraph_t *arg1 = (Agraph_t *) 0 ;
    Agnode_t *arg2 = (Agnode_t *) 0 ;
    int arg3 ;
    Agnode_t *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOi:agsubnode",&obj0,&obj1,&arg3)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agraph_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Agnode_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (Agnode_t *)agsubnode(arg1,arg2,arg3);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Agnode_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agsubedge(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agraph_t *arg1 = (Agraph_t *) 0 ;
    Agedge_t *arg2 = (Agedge_t *) 0 ;
    int arg3 ;
    Agedge_t *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOi:agsubedge",&obj0,&obj1,&arg3)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agraph_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Agedge_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (Agedge_t *)agsubedge(arg1,arg2,arg3);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Agedge_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agdelsubg(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agraph_t *arg1 = (Agraph_t *) 0 ;
    Agraph_t *arg2 = (Agraph_t *) 0 ;
    long result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:agdelsubg",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agraph_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Agraph_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (long)agdelsubg(arg1,arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agnode(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agraph_t *arg1 = (Agraph_t *) 0 ;
    char *arg2 ;
    int arg3 ;
    Agnode_t *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOi:agnode",&obj0,&obj1,&arg3)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agraph_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        if (obj1 == Py_None) {
            arg2 = 0;
        } else if (!PyString_Check(obj1)) {
            PyErr_SetString(PyExc_TypeError, "not a valid string");
            return NULL;
        } else arg2 = PyString_AsString(obj1);
    }
    {
        result = (Agnode_t *)agnode(arg1,arg2,arg3);
        
        if (!result) {
            PyErr_SetString(PyExc_KeyError,"agnode: no key");
            return NULL;
        }
    }
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Agnode_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agfstnode(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agraph_t *arg1 = (Agraph_t *) 0 ;
    Agnode_t *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:agfstnode",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agraph_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (Agnode_t *)agfstnode(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Agnode_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agnxtnode(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agnode_t *arg1 = (Agnode_t *) 0 ;
    Agnode_t *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:agnxtnode",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agnode_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (Agnode_t *)agnxtnode(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Agnode_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agdelnode(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agnode_t *arg1 = (Agnode_t *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:agdelnode",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agnode_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        result = (int)agdelnode(arg1);
        
        if (result==-1) {
            PyErr_SetString(PyExc_KeyError,"agdelnode: no key");
            return NULL;
        }
    }
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agedge(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agnode_t *arg1 = (Agnode_t *) 0 ;
    Agnode_t *arg2 = (Agnode_t *) 0 ;
    char *arg3 ;
    int arg4 ;
    Agedge_t *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOOi:agedge",&obj0,&obj1,&obj2,&arg4)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agnode_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Agnode_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        if (obj2 == Py_None) {
            arg3 = 0;
        } else if (!PyString_Check(obj2)) {
            PyErr_SetString(PyExc_TypeError, "not a valid string");
            return NULL;
        } else arg3 = PyString_AsString(obj2);
    }
    {
        result = (Agedge_t *)agedge(arg1,arg2,arg3,arg4);
        
        if (!result) {
            PyErr_SetString(PyExc_KeyError,"agedge: no key");
            return NULL;
        }
    }
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Agedge_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_aghead(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agedge_t *arg1 = (Agedge_t *) 0 ;
    Agnode_t *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:aghead",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agedge_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (Agnode_t *)aghead(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Agnode_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agtail(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agedge_t *arg1 = (Agedge_t *) 0 ;
    Agnode_t *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:agtail",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agedge_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (Agnode_t *)agtail(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Agnode_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agfstedge(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agnode_t *arg1 = (Agnode_t *) 0 ;
    Agedge_t *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:agfstedge",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agnode_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (Agedge_t *)agfstedge(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Agedge_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agnxtedge(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agedge_t *arg1 = (Agedge_t *) 0 ;
    Agnode_t *arg2 = (Agnode_t *) 0 ;
    Agedge_t *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:agnxtedge",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agedge_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Agnode_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (Agedge_t *)agnxtedge(arg1,arg2);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Agedge_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agfstin(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agnode_t *arg1 = (Agnode_t *) 0 ;
    Agedge_t *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:agfstin",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agnode_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (Agedge_t *)agfstin(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Agedge_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agnxtin(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agedge_t *arg1 = (Agedge_t *) 0 ;
    Agedge_t *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:agnxtin",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agedge_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (Agedge_t *)agnxtin(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Agedge_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agfstout(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agnode_t *arg1 = (Agnode_t *) 0 ;
    Agedge_t *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:agfstout",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agnode_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (Agedge_t *)agfstout(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Agedge_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agnxtout(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agedge_t *arg1 = (Agedge_t *) 0 ;
    Agedge_t *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:agnxtout",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agedge_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (Agedge_t *)agnxtout(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Agedge_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agdeledge(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agedge_t *arg1 = (Agedge_t *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:agdeledge",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agedge_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        result = (int)agdeledge(arg1);
        
        if (result==-1) {
            PyErr_SetString(PyExc_KeyError,"No key");
            return NULL;
        }
    }
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agattr(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agraph_t *arg1 = (Agraph_t *) 0 ;
    int arg2 ;
    char *arg3 ;
    char *arg4 ;
    Agsym_t *result;
    PyObject * obj0 = 0 ;
    PyObject * obj2 = 0 ;
    PyObject * obj3 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OiOO:agattr",&obj0,&arg2,&obj2,&obj3)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agraph_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        if (obj2 == Py_None) {
            arg3 = 0;
        } else if (!PyString_Check(obj2)) {
            PyErr_SetString(PyExc_TypeError, "not a valid string");
            return NULL;
        } else arg3 = PyString_AsString(obj2);
    }
    {
        if (obj3 == Py_None) {
            arg4 = 0;
        } else if (!PyString_Check(obj3)) {
            PyErr_SetString(PyExc_TypeError, "not a valid string");
            return NULL;
        } else arg4 = PyString_AsString(obj3);
    }
    result = (Agsym_t *)agattr(arg1,arg2,arg3,arg4);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Agsym_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agattrsym(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    void *arg1 = (void *) 0 ;
    char *arg2 ;
    Agsym_t *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:agattrsym",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, 0, SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        if (obj1 == Py_None) {
            arg2 = 0;
        } else if (!PyString_Check(obj1)) {
            PyErr_SetString(PyExc_TypeError, "not a valid string");
            return NULL;
        } else arg2 = PyString_AsString(obj1);
    }
    result = (Agsym_t *)agattrsym(arg1,arg2);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Agsym_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agnxtattr(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agraph_t *arg1 = (Agraph_t *) 0 ;
    int arg2 ;
    Agsym_t *arg3 = (Agsym_t *) 0 ;
    Agsym_t *result;
    PyObject * obj0 = 0 ;
    PyObject * obj2 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OiO:agnxtattr",&obj0,&arg2,&obj2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agraph_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj2,(void **) &arg3, SWIGTYPE_p_Agsym_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        result = (Agsym_t *)agnxtattr(arg1,arg2,arg3);
        
        if (!result) {
            PyErr_SetString(PyExc_KeyError,"agnxtattr no key");
            return NULL;
        }
    }
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Agsym_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agget(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    void *arg1 = (void *) 0 ;
    char *arg2 ;
    char *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:agget",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, 0, SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        if (obj1 == Py_None) {
            arg2 = 0;
        } else if (!PyString_Check(obj1)) {
            PyErr_SetString(PyExc_TypeError, "not a valid string");
            return NULL;
        } else arg2 = PyString_AsString(obj1);
    }
    {
        result = (char *)agget(arg1,arg2);
        
        if (!strcmp(result,"")) {
            PyErr_SetString(PyExc_KeyError,arg2);
            return NULL;
        }
    }
    {
        resultobj = Py_BuildValue("s", result);
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agxget(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    void *arg1 = (void *) 0 ;
    Agsym_t *arg2 = (Agsym_t *) 0 ;
    char *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:agxget",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, 0, SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Agsym_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        result = (char *)agxget(arg1,arg2);
        
        if (!strcmp(result,"")) {
            PyErr_SetString(PyExc_KeyError,"No symbol");
            return NULL;
        }
    }
    {
        resultobj = Py_BuildValue("s", result);
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agset(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    void *arg1 = (void *) 0 ;
    char *arg2 ;
    char *arg3 ;
    int result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOO:agset",&obj0,&obj1,&obj2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, 0, SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        if (obj1 == Py_None) {
            arg2 = 0;
        } else if (!PyString_Check(obj1)) {
            PyErr_SetString(PyExc_TypeError, "not a valid string");
            return NULL;
        } else arg2 = PyString_AsString(obj1);
    }
    {
        if (obj2 == Py_None) {
            arg3 = 0;
        } else if (!PyString_Check(obj2)) {
            PyErr_SetString(PyExc_TypeError, "not a valid string");
            return NULL;
        } else arg3 = PyString_AsString(obj2);
    }
    {
        result = (int)agset(arg1,arg2,arg3);
        
        if (result==-1) {
            PyErr_SetString(PyExc_KeyError,"agset: no key");
            return NULL;
        }
    }
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agxset(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    void *arg1 = (void *) 0 ;
    Agsym_t *arg2 = (Agsym_t *) 0 ;
    char *arg3 ;
    int result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOO:agxset",&obj0,&obj1,&obj2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, 0, SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Agsym_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        if (obj2 == Py_None) {
            arg3 = 0;
        } else if (!PyString_Check(obj2)) {
            PyErr_SetString(PyExc_TypeError, "not a valid string");
            return NULL;
        } else arg3 = PyString_AsString(obj2);
    }
    result = (int)agxset(arg1,arg2,arg3);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agattrname(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agsym_t *arg1 = (Agsym_t *) 0 ;
    char *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:agattrname",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agsym_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (char *)agattrname(arg1);
    
    {
        resultobj = Py_BuildValue("s", result);
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agattrdefval(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agsym_t *arg1 = (Agsym_t *) 0 ;
    char *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:agattrdefval",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agsym_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (char *)agattrdefval(arg1);
    
    {
        resultobj = Py_BuildValue("s", result);
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agnnodes(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agraph_t *arg1 = (Agraph_t *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:agnnodes",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agraph_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)agnnodes(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agnedges(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agraph_t *arg1 = (Agraph_t *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:agnedges",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agraph_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)agnedges(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agdegree(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Agnode_t *arg1 = (Agnode_t *) 0 ;
    int arg2 ;
    int arg3 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oii:agdegree",&obj0,&arg2,&arg3)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Agnode_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)agdegree(arg1,arg2,arg3);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agraphof(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    void *arg1 = (void *) 0 ;
    Agraph_t *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:agraphof",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, 0, SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (Agraph_t *)agraphof(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Agraph_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_agnameof(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    void *arg1 = (void *) 0 ;
    char *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:agnameof",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, 0, SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (char *)agnameof(arg1);
    
    {
        resultobj = Py_BuildValue("s", result);
    }
    return resultobj;
    fail:
    return NULL;
}


static int _wrap_Agdirected_set(PyObject *_val) {
    {
        Agdesc_t * temp;
        if ((SWIG_ConvertPtr(_val, (void **) &temp, SWIGTYPE_p_Agdesc_t, SWIG_POINTER_EXCEPTION)) == -1) {
            PyErr_SetString(PyExc_TypeError, "C variable 'Agdirected (Agdesc_t)'");
            return 1;
        }
        Agdirected = *((Agdesc_t *) temp);
    }
    return 0;
}


static PyObject *_wrap_Agdirected_get() {
    PyObject *pyobj;
    
    pyobj = SWIG_NewPointerObj((void *) &Agdirected, SWIGTYPE_p_Agdesc_t, 0);
    return pyobj;
}


static int _wrap_Agstrictdirected_set(PyObject *_val) {
    {
        Agdesc_t * temp;
        if ((SWIG_ConvertPtr(_val, (void **) &temp, SWIGTYPE_p_Agdesc_t, SWIG_POINTER_EXCEPTION)) == -1) {
            PyErr_SetString(PyExc_TypeError, "C variable 'Agstrictdirected (Agdesc_t)'");
            return 1;
        }
        Agstrictdirected = *((Agdesc_t *) temp);
    }
    return 0;
}


static PyObject *_wrap_Agstrictdirected_get() {
    PyObject *pyobj;
    
    pyobj = SWIG_NewPointerObj((void *) &Agstrictdirected, SWIGTYPE_p_Agdesc_t, 0);
    return pyobj;
}


static int _wrap_Agundirected_set(PyObject *_val) {
    {
        Agdesc_t * temp;
        if ((SWIG_ConvertPtr(_val, (void **) &temp, SWIGTYPE_p_Agdesc_t, SWIG_POINTER_EXCEPTION)) == -1) {
            PyErr_SetString(PyExc_TypeError, "C variable 'Agundirected (Agdesc_t)'");
            return 1;
        }
        Agundirected = *((Agdesc_t *) temp);
    }
    return 0;
}


static PyObject *_wrap_Agundirected_get() {
    PyObject *pyobj;
    
    pyobj = SWIG_NewPointerObj((void *) &Agundirected, SWIGTYPE_p_Agdesc_t, 0);
    return pyobj;
}


static int _wrap_Agstrictundirected_set(PyObject *_val) {
    {
        Agdesc_t * temp;
        if ((SWIG_ConvertPtr(_val, (void **) &temp, SWIGTYPE_p_Agdesc_t, SWIG_POINTER_EXCEPTION)) == -1) {
            PyErr_SetString(PyExc_TypeError, "C variable 'Agstrictundirected (Agdesc_t)'");
            return 1;
        }
        Agstrictundirected = *((Agdesc_t *) temp);
    }
    return 0;
}


static PyObject *_wrap_Agstrictundirected_get() {
    PyObject *pyobj;
    
    pyobj = SWIG_NewPointerObj((void *) &Agstrictundirected, SWIGTYPE_p_Agdesc_t, 0);
    return pyobj;
}


static PyMethodDef SwigMethods[] = {
	 { (char *)"agopen", _wrap_agopen, METH_VARARGS },
	 { (char *)"agclose", _wrap_agclose, METH_VARARGS },
	 { (char *)"agread", _wrap_agread, METH_VARARGS },
	 { (char *)"agwrite", _wrap_agwrite, METH_VARARGS },
	 { (char *)"agisundirected", _wrap_agisundirected, METH_VARARGS },
	 { (char *)"agisdirected", _wrap_agisdirected, METH_VARARGS },
	 { (char *)"agisstrict", _wrap_agisstrict, METH_VARARGS },
	 { (char *)"agsubg", _wrap_agsubg, METH_VARARGS },
	 { (char *)"agfstsubg", _wrap_agfstsubg, METH_VARARGS },
	 { (char *)"agnxtsubg", _wrap_agnxtsubg, METH_VARARGS },
	 { (char *)"agparent", _wrap_agparent, METH_VARARGS },
	 { (char *)"agroot", _wrap_agroot, METH_VARARGS },
	 { (char *)"agsubnode", _wrap_agsubnode, METH_VARARGS },
	 { (char *)"agsubedge", _wrap_agsubedge, METH_VARARGS },
	 { (char *)"agdelsubg", _wrap_agdelsubg, METH_VARARGS },
	 { (char *)"agnode", _wrap_agnode, METH_VARARGS },
	 { (char *)"agfstnode", _wrap_agfstnode, METH_VARARGS },
	 { (char *)"agnxtnode", _wrap_agnxtnode, METH_VARARGS },
	 { (char *)"agdelnode", _wrap_agdelnode, METH_VARARGS },
	 { (char *)"agedge", _wrap_agedge, METH_VARARGS },
	 { (char *)"aghead", _wrap_aghead, METH_VARARGS },
	 { (char *)"agtail", _wrap_agtail, METH_VARARGS },
	 { (char *)"agfstedge", _wrap_agfstedge, METH_VARARGS },
	 { (char *)"agnxtedge", _wrap_agnxtedge, METH_VARARGS },
	 { (char *)"agfstin", _wrap_agfstin, METH_VARARGS },
	 { (char *)"agnxtin", _wrap_agnxtin, METH_VARARGS },
	 { (char *)"agfstout", _wrap_agfstout, METH_VARARGS },
	 { (char *)"agnxtout", _wrap_agnxtout, METH_VARARGS },
	 { (char *)"agdeledge", _wrap_agdeledge, METH_VARARGS },
	 { (char *)"agattr", _wrap_agattr, METH_VARARGS },
	 { (char *)"agattrsym", _wrap_agattrsym, METH_VARARGS },
	 { (char *)"agnxtattr", _wrap_agnxtattr, METH_VARARGS },
	 { (char *)"agget", _wrap_agget, METH_VARARGS },
	 { (char *)"agxget", _wrap_agxget, METH_VARARGS },
	 { (char *)"agset", _wrap_agset, METH_VARARGS },
	 { (char *)"agxset", _wrap_agxset, METH_VARARGS },
	 { (char *)"agattrname", _wrap_agattrname, METH_VARARGS },
	 { (char *)"agattrdefval", _wrap_agattrdefval, METH_VARARGS },
	 { (char *)"agnnodes", _wrap_agnnodes, METH_VARARGS },
	 { (char *)"agnedges", _wrap_agnedges, METH_VARARGS },
	 { (char *)"agdegree", _wrap_agdegree, METH_VARARGS },
	 { (char *)"agraphof", _wrap_agraphof, METH_VARARGS },
	 { (char *)"agnameof", _wrap_agnameof, METH_VARARGS },
	 { NULL, NULL }
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__p_FILE[] = {{"_p_FILE", 0, "FILE *", 0},{"_p_FILE"},{0}};
static swig_type_info _swigt__p_Agedge_t[] = {{"_p_Agedge_t", 0, "Agedge_t *", 0},{"_p_Agedge_t"},{0}};
static swig_type_info _swigt__p_Agsym_t[] = {{"_p_Agsym_t", 0, "Agsym_t *", 0},{"_p_Agsym_t"},{0}};
static swig_type_info _swigt__p_Agraph_t[] = {{"_p_Agraph_t", 0, "Agraph_t *", 0},{"_p_Agraph_t"},{0}};
static swig_type_info _swigt__p_Agdesc_t[] = {{"_p_Agdesc_t", 0, "Agdesc_t *", 0},{"_p_Agdesc_t"},{0}};
static swig_type_info _swigt__p_Agnode_t[] = {{"_p_Agnode_t", 0, "Agnode_t *", 0},{"_p_Agnode_t"},{0}};
static swig_type_info _swigt__p_Agdisc_t[] = {{"_p_Agdisc_t", 0, "Agdisc_t *", 0},{"_p_Agdisc_t"},{0}};

static swig_type_info *swig_types_initial[] = {
_swigt__p_FILE, 
_swigt__p_Agedge_t, 
_swigt__p_Agsym_t, 
_swigt__p_Agraph_t, 
_swigt__p_Agdesc_t, 
_swigt__p_Agnode_t, 
_swigt__p_Agdisc_t, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

static swig_const_info swig_const_table[] = {
{ SWIG_PY_INT,     (char *)"AGRAPH", (long) 0, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"AGNODE", (long) 1, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"AGOUTEDGE", (long) 2, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"AGINEDGE", (long) 3, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"AGEDGE", (long) 2, 0, 0, 0},
{0}};

#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
extern "C"
#endif
SWIGEXPORT(void) SWIG_init(void) {
    static PyObject *SWIG_globals = 0; 
    static int       typeinit = 0;
    PyObject *m, *d;
    int       i;
    if (!SWIG_globals) SWIG_globals = SWIG_newvarlink();
    m = Py_InitModule((char *) SWIG_name, SwigMethods);
    d = PyModule_GetDict(m);
    
    if (!typeinit) {
        for (i = 0; swig_types_initial[i]; i++) {
            swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
        }
        typeinit = 1;
    }
    SWIG_InstallConstants(d,swig_const_table);
    
    PyDict_SetItemString(d,(char*)"cvar", SWIG_globals);
    SWIG_addvarlink(SWIG_globals,(char*)"Agdirected",_wrap_Agdirected_get, _wrap_Agdirected_set);
    SWIG_addvarlink(SWIG_globals,(char*)"Agstrictdirected",_wrap_Agstrictdirected_get, _wrap_Agstrictdirected_set);
    SWIG_addvarlink(SWIG_globals,(char*)"Agundirected",_wrap_Agundirected_get, _wrap_Agundirected_set);
    SWIG_addvarlink(SWIG_globals,(char*)"Agstrictundirected",_wrap_Agstrictundirected_get, _wrap_Agstrictundirected_set);
}

