import os
from glob import glob
import shutil


def _get_sg_image_scraper():
    """Return the callable scraper to be used by Sphinx-Gallery.

    It allows PyGraphviz users to just use strings as they already can for
    'matplotlib' and 'mayavi'. Details on this implementation can be found in
    `sphinx-gallery/sphinx-gallery/494`_

    .. _sphinx-gallery/sphinx-gallery/494: https://github.com/sphinx-gallery/sphinx-gallery/pull/494
    """
    return PNGScraper()


class PNGScraper:
    """A callable image scraper for png outputs from pygraphviz examples
    for sphinx-gallery.

    Can be used to collect `.png` files generated by pygraphviz in
    sphinx-gallery examples by adding the following to the ``conf.py``::

        sphinx_gallery_conf = {
            ...
            'image_scrapers': ('matplotlib', 'pygraphviz'),
        }

    Only ``.png`` files whose names appear in the code block that was just
    executed are collected (e.g., ``"star.png"`` in ``A.draw("star.png")``), so
    examples in the same directory can be built in parallel (sphinx-gallery's
    ``parallel`` option) without collecting each other's images.

    This class is based on the recipe provide in [1]_.

    References
    ----------
    .. [1] sphinx-gallery documentation - custom image scraper.
       https://sphinx-gallery.github.io/stable/advanced.html
    """

    def __repr__(self):
        return "PNGScraper"

    def __call__(self, block, block_vars, gallery_conf):
        """
        Scrape .png images created by pygraphviz examples.

        Invoked by sphinx-gallery.

        Parameters
        ----------
        block : tuple
            A tuple containing the (label, content, line_number) of the
            block. Only PNG files whose names appear in ``content`` are
            collected. If ``None``, all PNG files in the example's directory are
            collected.
        block_vars : dict
            Dict of block variables
        gallery_conf : dict
            Mapping of sphinx-gallery configuration values

        Returns
        -------
        str :
            rST-formatted string containing the generated images. This will
            be rendered to HTML during the ``sphinx-build`` process.
        """
        try:
            from sphinx_gallery.scrapers import figure_rst
        except ImportError as e:
            raise ImportError("You must install `sphinx_gallery`") from e

        # Find the PNG files in the directory of this example that were written
        # by this code block
        path_current_example = os.path.dirname(block_vars["src_file"])
        pngs = sorted(glob(os.path.join(path_current_example, "*.png")))
        if block is not None:
            pngs = [png for png in pngs if os.path.basename(png) in block[1]]

        # Move PNGs to the sphinx-gallery output dir (so they can't be collected
        # twice, while a later example can still write a file with the same name)
        image_names = []
        image_path_iterator = block_vars["image_path_iterator"]
        for png in pngs:
            this_image_path = next(image_path_iterator)
            image_names.append(this_image_path)
            shutil.move(png, this_image_path)

        # Use figure_rst to generate rST for image files
        return figure_rst(image_names, gallery_conf["src_dir"])
