name: Run Windows Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_windows:

    runs-on: windows-latest

    # Add matrix here via "strategy:"

    steps:
    - uses: actions/checkout@v2

    - name: Python Setup
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install Graphviz
      run: |
        choco install graphviz

    - name: Install Testing Dependencies
      run: |
        python -m venv testenv
        cmd.exe /c '\testenv\bin\activate.bat'
        python -m pip install -r requirements/test.txt
        python -m pip install -e .

    - name: Run Tests
      run: |
        pytest -vv pygraphviz
